# Định danh trình nạp mod bắt buộc của NeoForge
modLoader="javafml"

# Phiên bản cấu hình ngôn ngữ của tệp TOML
loaderVersion="[1,)"

# Giấy phép bản quyền của bản mod
license="MIT"

# Khai báo cấu hình tệp cấu trúc Mixin để hệ thống tự động kích hoạt mã nguồn Java
# Đoạn này cực kỳ quan trọng để NeoForge biết có file Mixin cần chạy ngầm
[[mixins]]
config="personalhelperfriend.mixins.json"

[[mods]]
# Mod ID viết thường, bắt buộc trùng khớp với cấu hình hệ thống
modId="personal_helper_friends_remake"

# Phiên bản hiện tại của bản Addon Mod
version="1.0.0"

# Tên hiển thị của bản mod trong giao diện danh sách Mod của Minecraft
displayName="personal helper friends remake"

# Tên của bạn (Tác giả tạo ra bản Mesh Mod này)
authors="helo"

# Đường dẫn ảnh đại diện nếu có (Có thể bỏ trống)
logoFile="icon.png"

# Mô tả ngắn gọn nhưng đầy đủ về tính năng của bản mod
description='''
This is a mod that makes the Personal Helper Friends mod more similar to thatmob's original video.
'''

# Thiết lập hệ thống phụ thuộc (Dependencies)
# Đoạn này bắt buộc game Minecraft và Mod gốc của tác giả phải được cài đặt trước
[[dependencies.verity_monster_final_addon]]
    modId="neoforge"
    type="required"
    versionRange="[1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.verity_monster_final_addon]]
    # Mod ID chuẩn xác của bản mod gốc (bắt buộc phải có thì Addon mới chạy)
    modId="personalhelperfriend" 
    type="required"
    versionRange="[0,)"
    ordering="AFTER" # Ép bản addon của bạn phải tải SAU mod gốc để đè được code Java
    side="CLIENT"
